name: Provision Identity

on:
    workflow_call:
      outputs:
        aagIdentityResourceId:
          description: The resource id of the user assigned managed identity for the AAG
          value: ${{ jobs.aks-infra-identity.outputs.aagIdentityResourceId }}
        aksIdentityResourceId:
          description: The resource id of the user assigned managed identity for the AKS cluster
          value: ${{ jobs.aks-infra-identity.outputs.aksIdentityResourceId }}

jobs:
    aks-infra-identity:
        environment: endor
        runs-on: [ubuntu-latest]
        permissions:
          contents: read
          id-token: write
        steps:
          - name: Repo Self-Checkout
            uses: actions/checkout@v3
    
          - name: Azure Login
            uses: azure/login@v1        
            with:         
                tenant-id: ${{ secrets.TENANT_ID }}
                client-id: ${{ secrets.CLIENT_ID }}
                subscription-id: ${{ vars.SUBSCRIPTION_ID }}
                enable-AzPSSession: true
    
          - uses: azure/arm-deploy@v1
            name: RG Identity
            id: resourceGroupIdentity
            with:
              scope: subscription
              region: ${{ vars.AZURE_REGION }}
              subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
              deploymentName: rg-identity
              template: arm/templates/resource-group.json
              parameters: >
                arm/parameters/resource-group.identity.json
                resourceGroupLocation=${{ vars.AZURE_REGION }}
          
          - uses: azure/arm-deploy@v1
            name: Managed Identity for AAG
            id: uami-aag
            with:
              template: arm/templates/managed-identity.json
              parameters: >
                arm/parameters/managed-identity.aag.json
              resourceGroupName: ${{ steps.resourceGroupIdentity.outputs.resourceGroupName }}
              deploymentName: managed-identity-aag
          
          - uses: azure/arm-deploy@v1
            name: Managed Identity for AKS
            id: uami-aks
            with:
              template: arm/templates/managed-identity.json
              parameters: >
                arm/parameters/managed-identity.aks.json
              resourceGroupName: ${{ steps.resourceGroupIdentity.outputs.resourceGroupName }}
              deploymentName: managed-identity-aks
        outputs:
          aagIdentityResourceId: ${{ steps.uami-aag.outputs.userAssignedIdentityResourceId }}
          aksIdentityResourceId: ${{ steps.uami-aks.outputs.userAssignedIdentityResourceId }}